export type PantryItemDef = {
  name: string;
  storage: 'cold' | 'frozen' | 'shelf';
};

export const pantryCategories: { name: string; items: PantryItemDef[] }[] = [
  {
    name: 'PRODUCE',
    items: [
      { name: 'Lemons', storage: 'shelf' },
      { name: 'Limes', storage: 'shelf' },
      { name: 'Garlic', storage: 'shelf' },
      { name: 'Onions', storage: 'shelf' },
      { name: 'Spinach', storage: 'cold' },
      { name: 'Tomatoes', storage: 'shelf' },
      { name: 'Avocado', storage: 'shelf' },
      { name: 'Carrots', storage: 'cold' },
      { name: 'Celery', storage: 'cold' },
      { name: 'Bell peppers', storage: 'cold' },
      { name: 'Potatoes', storage: 'shelf' },
      { name: 'Sweet potatoes', storage: 'shelf' },
      { name: 'Broccoli', storage: 'cold' },
      { name: 'Cucumber', storage: 'cold' },
      { name: 'Zucchini', storage: 'cold' },
      { name: 'Mushrooms', storage: 'cold' },
      { name: 'Green onions', storage: 'cold' },
      { name: 'Ginger', storage: 'cold' },
      { name: 'Cilantro', storage: 'cold' },
      { name: 'Parsley', storage: 'cold' },
      { name: 'Basil', storage: 'shelf' },
      { name: 'Bananas', storage: 'shelf' },
      { name: 'Apples', storage: 'cold' },
      { name: 'Berries', storage: 'cold' },
    ],
  },
  {
    name: 'MEATS & POULTRY',
    items: [
      { name: 'Chicken thighs', storage: 'cold' },
      { name: 'Chicken breast', storage: 'cold' },
      { name: 'Ground beef', storage: 'cold' },
      { name: 'Ground turkey', storage: 'cold' },
      { name: 'Bacon', storage: 'cold' },
      { name: 'Sausage', storage: 'cold' },
      { name: 'Steak', storage: 'cold' },
      { name: 'Pork chops', storage: 'cold' },
      { name: 'Ham', storage: 'cold' },
      { name: 'Deli meat', storage: 'cold' },
    ],
  },
  {
    name: 'SEAFOOD',
    items: [
      { name: 'Salmon', storage: 'cold' },
      { name: 'Shrimp', storage: 'cold' },
      { name: 'Tilapia', storage: 'cold' },
      { name: 'Tuna', storage: 'cold' },
      { name: 'Canned tuna', storage: 'shelf' },
    ],
  },
  {
    name: 'DAIRY & EGGS',
    items: [
      { name: 'Milk', storage: 'cold' },
      { name: 'Eggs', storage: 'cold' },
      { name: 'Cheddar cheese', storage: 'cold' },
      { name: 'Mozzarella', storage: 'cold' },
      { name: 'Parmesan', storage: 'cold' },
      { name: 'Butter', storage: 'cold' },
      { name: 'Greek yogurt', storage: 'cold' },
      { name: 'Sour cream', storage: 'cold' },
      { name: 'Cream cheese', storage: 'cold' },
      { name: 'Heavy cream', storage: 'cold' },
    ],
  },
  {
    name: 'GRAINS & PASTA',
    items: [
      { name: 'Rice', storage: 'shelf' },
      { name: 'Spaghetti', storage: 'shelf' },
      { name: 'Penne', storage: 'shelf' },
      { name: 'Bread', storage: 'shelf' },
      { name: 'Tortillas', storage: 'shelf' },
      { name: 'Quinoa', storage: 'shelf' },
      { name: 'Oats', storage: 'shelf' },
      { name: 'Couscous', storage: 'shelf' },
    ],
  },
  {
    name: 'CANNED & JARRED',
    items: [
      { name: 'Black beans', storage: 'shelf' },
      { name: 'Chickpeas', storage: 'shelf' },
      { name: 'Diced tomatoes', storage: 'shelf' },
      { name: 'Tomato sauce', storage: 'shelf' },
      { name: 'Tomato paste', storage: 'shelf' },
      { name: 'Corn', storage: 'shelf' },
      { name: 'Green beans', storage: 'shelf' },
      { name: 'Chicken broth', storage: 'shelf' },
      { name: 'Vegetable broth', storage: 'shelf' },
      { name: 'Coconut milk', storage: 'shelf' },
    ],
  },
  {
    name: 'BAKING',
    items: [
      { name: 'Flour', storage: 'shelf' },
      { name: 'Sugar', storage: 'shelf' },
      { name: 'Brown sugar', storage: 'shelf' },
      { name: 'Baking powder', storage: 'shelf' },
      { name: 'Baking soda', storage: 'shelf' },
      { name: 'Vanilla extract', storage: 'shelf' },
      { name: 'Chocolate chips', storage: 'shelf' },
      { name: 'Honey', storage: 'shelf' },
    ],
  },
  {
    name: 'SPICES & SEASONINGS',
    items: [
      { name: 'Salt', storage: 'shelf' },
      { name: 'Black pepper', storage: 'shelf' },
      { name: 'Garlic powder', storage: 'shelf' },
      { name: 'Onion powder', storage: 'shelf' },
      { name: 'Paprika', storage: 'shelf' },
      { name: 'Cumin', storage: 'shelf' },
      { name: 'Chili powder', storage: 'shelf' },
      { name: 'Italian seasoning', storage: 'shelf' },
      { name: 'Cinnamon', storage: 'shelf' },
      { name: 'Red pepper flakes', storage: 'shelf' },
    ],
  },
  {
    name: 'CONDIMENTS & SAUCES',
    items: [
      { name: 'Olive oil', storage: 'shelf' },
      { name: 'Soy sauce', storage: 'shelf' },
      { name: 'Ketchup', storage: 'cold' },
      { name: 'Mustard', storage: 'cold' },
      { name: 'Mayonnaise', storage: 'cold' },
      { name: 'Hot sauce', storage: 'shelf' },
      { name: 'BBQ sauce', storage: 'cold' },
      { name: 'Salsa', storage: 'cold' },
      { name: 'Ranch dressing', storage: 'cold' },
      { name: 'Worcestershire sauce', storage: 'shelf' },
    ],
  },
  {
    name: 'FROZEN',
    items: [
      { name: 'Frozen peas', storage: 'frozen' },
      { name: 'Frozen corn', storage: 'frozen' },
      { name: 'Frozen berries', storage: 'frozen' },
      { name: 'Frozen pizza', storage: 'frozen' },
      { name: 'Ice cream', storage: 'frozen' },
      { name: 'Frozen french fries', storage: 'frozen' },
    ],
  },
  {
    name: 'LEGUMES & BEANS',
    items: [
      { name: 'Lentils', storage: 'shelf' },
      { name: 'Dried black beans', storage: 'shelf' },
      { name: 'Split peas', storage: 'shelf' },
    ],
  },
  {
    name: 'BEVERAGES',
    items: [
      { name: 'Coffee', storage: 'shelf' },
      { name: 'Tea', storage: 'shelf' },
      { name: 'Orange juice', storage: 'cold' },
      { name: 'Sparkling water', storage: 'shelf' },
    ],
  },
  {
    name: 'SNACKS',
    items: [
      { name: 'Chips', storage: 'shelf' },
      { name: 'Crackers', storage: 'shelf' },
      { name: 'Peanut butter', storage: 'shelf' },
      { name: 'Granola bars', storage: 'shelf' },
    ],
  },
];